//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorDelightsProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminLogin
    {
        [Key]
        public short AdminId { get; set; }
        [Required]
        [Display(Name ="Username")]
        public string Username { get; set; }
        [Required]
        [DataType(DataType.Password,ErrorMessage ="Password Is Not Valid")]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.EmailAddress, ErrorMessage ="Email is Not Valid")]

        public string EmailAddress { get; set; }
        [Required]
        
        public decimal Mobile_No { get; set; }
        [Required]
        [Display(Name="FullName")]
        [MaxLength(50)]
        public string Name { get; set; }
    }
}
