//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorDelightsProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class FoodItem
    {
        public short FoodId { get; set; }
        public short RestaurantId { get; set; }
        [Required(ErrorMessage ="Please Enter the Item Name")]
        [MaxLength(50,ErrorMessage ="Item Name should not exceed more than 50 characters")]
        public string Item_name { get; set; }
        [Required(ErrorMessage ="Please Enter the Price")]
        
        public int Price { get; set; }
        [Required(ErrorMessage ="Please Upload Image")]
        public string Item_Image { get; set; }
        public HttpPostedFileBase Imagefile { get; set; }
    }
}
