//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorDelightsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public short HistoryId { get; set; }
        public short OrderId { get; set; }
        public string Restaurantname { get; set; }
        public short FoodId { get; set; }
        public string Itemname { get; set; }
        public int Price { get; set; }
        public string itemimage { get; set; }
        public short Quantity { get; set; }
        public short CustomerId { get; set; }
        public string DeliveryAddress { get; set; }
        public bool Isconfirmed { get; set; }
    }
}
