//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorDelightsProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Registration
    {
        [Key]
        public short CustomerId { get; set; }
        [Required(ErrorMessage ="Username is required")]
        [MaxLength(50,ErrorMessage =("Username should not exceed more than 50 characters"))]
        [Display(Name = "Username")]
        public string Username { get; set; }
        [Required(ErrorMessage ="Password is Required")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Required(ErrorMessage ="First Name is Required")]
        [Display(Name = "First Name")]
        [MaxLength(50, ErrorMessage = ("Firstname should not exceed more than 50 characters"))]
        public string Firstname { get; set; }
        [Required(ErrorMessage ="Last Name is required")]
        [Display(Name = "Last Name")]
        [MaxLength(50, ErrorMessage = ("Lastname should not exceed more than 50 characters"))]
        public string Lastname { get; set; }
        [Required(ErrorMessage = "Email is required")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Email is not valid")]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required(ErrorMessage ="Mobile.No is Required")]
        [Display(Name = "Mobile")]
        public decimal Mobile { get; set; }
    }
}
