//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorDelightsProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Restaurant
    {
        public short RestaurantId { get; set; }
        [Required(ErrorMessage = "Please Enter Restaurant Name")]
        [MaxLength(50, ErrorMessage = "Name should not exceed more then 50 characters")]
        public string RestaurantName { get; set; }
        public string RestaurantType { get; set; }
        [Required(ErrorMessage = "please Enter Restaurant Location")]
        [MaxLength(50, ErrorMessage = "Location should not exceed more then 50 characters")]
        public string RestaurantLocation { get; set; }
        [Range(0.1, 5.0, ErrorMessage = "Rate on scale 0 to 5")]
        public decimal RestaurantRating { get; set; }
        [Display(Name = "Delivery Time(In Mins)")]
        [Required]
        [MaxLength(9)]
        public string DeliveryTime { get; set; }
        [Required(ErrorMessage = "Please Upload Image")]
        public string RestaurantImage { get; set; }

        public HttpPostedFileBase Imagefile { get; set; }
        public bool Isclosed { get; set; }
    }
}
